apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-service
  labels:
    app: office-service
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office-service 
  template:
    metadata:
      labels:
        app: office-service 
    spec:
      containers:
      - name: office-service
        image: saloyiana/department-service
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: office-service
spec:
  type: NodePort
  selector:
    app: office-servicede
  ports:
    - port: 80
      targetPort: 80
